[package]
name = "use_art"
version = "0.1.0"
authors = ["hjiang <hjiang@sse.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artest = "0.2.0"